name: issue created

on:
  issues:
    types: [edited, opened]

jobs:
  add_fact:
    name: add a new fact if appropriate
    runs-on: ubuntu-latest

    steps:
      - uses: mgwalker/action-is-in-org@90d0af2865ef9684e2beb30302c217524fc9f456
        with:
          orgs: 18f cloud-gov digital-analytics-program digitalgov presidential-innovation-fellows usagov uswds
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
        with:
          ref: main
      - uses: actions/setup-node@d6e3b5539ed7e5ccd26c3459e26c7c817f4e9068
        with:
          node-version: 16
          cache: npm
      - run: npm install --production
      - run: node addFact.js
        working-directory: ./.github/workflows
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}