name: JSON validation

on: [pull_request]

jobs:
  schema_validation:
    name: JSON files are valid
    runs-on: ubuntu-latest
    container: node:latest
    steps:
      - uses: actions/checkout@v2
      - name: install validator
        run: npm install joi@^17.2.1
      - name: validate all documents
        run: node ./.github/workflows/validate.js

  # Enable automatic merging on pull requests, so that once tests pass, the
  # pull request will merge itself. No waiting. Let's simplify this thing!
  merge:
    name: turn on auto-merge
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@af513c7a016048ae468971c52ed77d9562c7c819
      - uses: mgwalker/action-is-in-orgs@v2.0
        id: org-check
        with:
          orgs: 18f cloud-gov digital-analytics-program digitalgov presidential-innovation-fellows usagov uswds
      - run: echo "--${{ steps.org-check.in_orgs }}--"
      - if: ${{ steps.org-check.in_orgs == 'true' || github.actor == 'dependabot[bot]' }}
        run: gh pr merge "$GITHUB_HEAD_REF" --auto --squash
